name: record_example
description: Demonstrates how to use the record plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  path_provider: ^2.0.1
  audioplayers: ^1.0.1

  flutter:
    sdk: flutter

  record:
    path: ../

dependency_overrides:
  record_platform_interface:
    path: ../../record_platform_interface
  record_web:
    path: ../../record_web
  record_windows:
    path: ../../record_windows
  record_macos:
    path: ../../record_macos
  record_linux:
    path: ../../record_linux

dev_dependencies:
  flutter_lints: ^2.0.0


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
